brew "cliproxyapi", restart_service: :changed
brew "gettext"
brew "mise"
brew "mole"
brew "officecli"
brew "zimfw"

cask "cc-switch"
cask "chatgpt"
cask "claude"
cask "dbeaver-community"
cask "drawio"
cask "ghostty"
cask "google-drive"
cask "obsidian"
cask "orbstack"
cask "session-manager-plugin"
cask "slack"
cask "zed"
