[mgr]
ratio          = [1, 3, 4]   # wider preview pane
show_hidden    = true
show_symlink   = true
scrolloff      = 5
sort_by        = "natural"   # foo2 before foo10
sort_dir_first = true
linemode       = "size"

[preview]
wrap          = "yes"
tab_size      = 4
max_width     = 1200
max_height    = 1200
image_quality = 90

# git.yazi: show git status in the linemode
[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
