[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
claude-code = "latest"
codex = "latest"
gcloud = "latest"
gh = "latest"
glab = "latest"
herdr = "latest"
node = "latest"
"npm:@fission-ai/openspec" = "1.11.0"
pnpm = "latest"
python = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
trusted_config_paths = [
    "~/workspace",
]
experimental = true
minimum_release_age = "0"
