# change color of status bar
set -g status-bg "colour60"
set -g status-fg "colour236"

# window-status format
setw -g window-status-format "#I:#W "
setw -g window-status-current-format "#[fg=colour254,bg=colour67] #I:#W"

# empty right panel of status bar
set -g status-right ""

# enable mouse operation
set -g mouse on
# vim key binding for copy mode
setw -g mode-keys vi

# copy to clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -bi"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -bi"

# Start window numbering at 1 instead of 0
set -g base-index 1

# Increase scrollback buffer
set -g history-limit 10000

# Make colors work properly
set -g default-terminal "screen-256color"

# Easier pane splitting (| and -)
bind | split-window -h
bind - split-window -v

set-option -g default-shell /bin/zsh

# set current directory to new panel
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

#set inactive/active window styles
set -g window-style 'bg=colour238'
set -g window-active-style 'bg=terminal'

# set the pane border colors 
set -g pane-border-style 'fg=colour235,bg=colour238' 
set -g pane-active-border-style 'fg=colour51,bg=colour236'
