setopt HIST_IGNORE_ALL_DUPS
bindkey -e
WORDCHARS=${WORDCHARS//[\/]}

alias src='cd $HOME/workspace'
alias gst='git status'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gb='git branch -vv'
alias gaa='git add .'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git pull'
alias gps='git push'
alias gpsf='git push -f'
alias gbd='git branch -D'
alias gss='git stash save'
alias grb='git rebase -i '
alias gcp='git cherry-pick '
alias glog='git log --reverse'

export PATH="$HOME/.local/bin:$PATH"

if (( ${+commands[mise]} )); then
  eval "$(mise activate zsh)"
fi
