setopt HIST_IGNORE_ALL_DUPS
bindkey -e
WORDCHARS=${WORDCHARS//[\/]}

ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

alias src='cd $HOME/workspace'
alias gst='git status'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gb='git branch -vv'
alias gaa='git add .'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git pull'
alias gps='git push'
alias gpsf='git push -f'
alias gbd='git branch -D'
alias gss='git stash save'
alias grb='git rebase -i '
alias gcp='git cherry-pick '
alias glog='git log --reverse'

export PATH="$HOME/.local/bin:$PATH"

ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim
ZIM_CONFIG_FILE=${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc}

if [[ -r ${ZIM_CONFIG_FILE} && ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE} ]] && (( ${+commands[brew]} )); then
  zimfw_script="$(brew --prefix zimfw 2>/dev/null)/share/zimfw.zsh"
  [[ -r ${zimfw_script} ]] && source "${zimfw_script}" init
fi

[[ -r ${ZIM_HOME}/init.zsh ]] && source "${ZIM_HOME}/init.zsh"

if (( ${+commands[mise]} )); then
  eval "$(mise activate zsh)"
fi

if (( ${+commands[starship]} )); then
  eval "$(starship init zsh)"
fi
